# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Laura
tagline:          No tengo tiempo para escribir
description:      "Blog de libros y programación"
url:              https://github.com/lauravelez
baseurl:          /

author:
  name:           'Laura Velez'
  url:            '#'

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/karloespiritu/blackdoc
